package model.common.serviceinterface;

import javax.jws.WebMethod;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 18 15:59:23 NOVT 2017
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/model/common/", name = "AppModuleService",
                    wsdlLocation = "model/common/serviceinterface/AppModuleService.wsdl")
@SDODatabinding(schemaLocation = "model/common/serviceinterface/AppModuleService.xsd")
public interface AppModuleService {
    public static final String NAME = "{/model/common/}AppModuleService";

    /**
     * Exported method DeleteAllEmps from AppModule.
     */
    @WebMethod(action = "/model/common/DeleteAllEmps", operationName = "DeleteAllEmps")
    @RequestWrapper(targetNamespace = "/model/common/types/", localName = "DeleteAllEmps")
    @ResponseWrapper(targetNamespace = "/model/common/types/", localName = "DeleteAllEmpsResponse")
    void DeleteAllEmps() throws ServiceException;
}

