package model;

import model.common.AppModule;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 18 15:47:39 NOVT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for CountriesView1.
     * @return CountriesView1
     */
    public ViewObjectImpl getCountriesView1() {
        return (ViewObjectImpl) findViewObject("CountriesView1");
    }
    public void DeleteAllEmps(){
        ViewObject vo = this.findViewObject("Employeesl");
    }
    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public ViewObjectImpl getDepartmentsView1() {
        return (ViewObjectImpl) findViewObject("DepartmentsView1");
    }

    /**
     * Container's getter for JobsView1.
     * @return JobsView1
     */
    public ViewObjectImpl getJobsView1() {
        return (ViewObjectImpl) findViewObject("JobsView1");
    }

    /**
     * Container's getter for EmpTranslated1.
     * @return EmpTranslated1
     */
    public ViewObjectImpl getEmpTranslated1() {
        return (ViewObjectImpl) findViewObject("EmpTranslated1");
    }

    /**
     * Container's getter for Jobs1View1.
     * @return Jobs1View1
     */
    public ViewObjectImpl getJobs1View1() {
        return (ViewObjectImpl) findViewObject("Jobs1View1");
    }

    /**
     * Container's getter for Countries2View1.
     * @return Countries2View1
     */
    public ViewObjectImpl getCountries2View1() {
        return (ViewObjectImpl) findViewObject("Countries2View1");
    }

    /**
     * Container's getter for Departments2View1.
     * @return Departments2View1
     */
    public ViewObjectImpl getDepartments2View1() {
        return (ViewObjectImpl) findViewObject("Departments2View1");
    }

    /**
     * Container's getter for EmpDetailsView1View1.
     * @return EmpDetailsView1View1
     */
    public ViewObjectImpl getEmpDetailsView1View1() {
        return (ViewObjectImpl) findViewObject("EmpDetailsView1View1");
    }

    /**
     * Container's getter for Employees1View1.
     * @return Employees1View1
     */
    public ViewObjectImpl getEmployees1View1() {
        return (ViewObjectImpl) findViewObject("Employees1View1");
    }

    /**
     * Container's getter for JobHistory1View1.
     * @return JobHistory1View1
     */
    public ViewObjectImpl getJobHistory1View1() {
        return (ViewObjectImpl) findViewObject("JobHistory1View1");
    }

    /**
     * Container's getter for Jobs2View1.
     * @return Jobs2View1
     */
    public ViewObjectImpl getJobs2View1() {
        return (ViewObjectImpl) findViewObject("Jobs2View1");
    }

    /**
     * Container's getter for Locations1View1.
     * @return Locations1View1
     */
    public ViewObjectImpl getLocations1View1() {
        return (ViewObjectImpl) findViewObject("Locations1View1");
    }

    /**
     * Container's getter for PsTxn1View1.
     * @return PsTxn1View1
     */
    public ViewObjectImpl getPsTxn1View1() {
        return (ViewObjectImpl) findViewObject("PsTxn1View1");
    }

    /**
     * Container's getter for Regions1View1.
     * @return Regions1View1
     */
    public ViewObjectImpl getRegions1View1() {
        return (ViewObjectImpl) findViewObject("Regions1View1");
    }

    /**
     * Container's getter for Countries2View1_1.
     * @return Countries2View1_1
     */
    public ViewObjectImpl getCountries2View1_1() {
        return (ViewObjectImpl) findViewObject("Countries2View1_1");
    }

    /**
     * Container's getter for Departments2View1_1.
     * @return Departments2View1_1
     */
    public ViewObjectImpl getDepartments2View1_1() {
        return (ViewObjectImpl) findViewObject("Departments2View1_1");
    }

    /**
     * Container's getter for Employees1View1_1.
     * @return Employees1View1_1
     */
    public ViewObjectImpl getEmployees1View1_1() {
        return (ViewObjectImpl) findViewObject("Employees1View1_1");
    }

    /**
     * Container's getter for EmpDetailsView1View1_1.
     * @return EmpDetailsView1View1_1
     */
    public ViewObjectImpl getEmpDetailsView1View1_1() {
        return (ViewObjectImpl) findViewObject("EmpDetailsView1View1_1");
    }

    /**
     * Container's getter for Jobs2View1_1.
     * @return Jobs2View1_1
     */
    public ViewObjectImpl getJobs2View1_1() {
        return (ViewObjectImpl) findViewObject("Jobs2View1_1");
    }

    /**
     * Container's getter for JobHistory1View1_1.
     * @return JobHistory1View1_1
     */
    public ViewObjectImpl getJobHistory1View1_1() {
        return (ViewObjectImpl) findViewObject("JobHistory1View1_1");
    }

    /**
     * Container's getter for Locations1View1_1.
     * @return Locations1View1_1
     */
    public ViewObjectImpl getLocations1View1_1() {
        return (ViewObjectImpl) findViewObject("Locations1View1_1");
    }

    /**
     * Container's getter for PsTxn1View1_1.
     * @return PsTxn1View1_1
     */
    public ViewObjectImpl getPsTxn1View1_1() {
        return (ViewObjectImpl) findViewObject("PsTxn1View1_1");
    }

    /**
     * Container's getter for Regions1View1_1.
     * @return Regions1View1_1
     */
    public ViewObjectImpl getRegions1View1_1() {
        return (ViewObjectImpl) findViewObject("Regions1View1_1");
    }

    /**
     * Container's getter for Departments2View2.
     * @return Departments2View2
     */
    public ViewObjectImpl getDepartments2View2() {
        return (ViewObjectImpl) findViewObject("Departments2View2");
    }

    /**
     * Container's getter for Employees1View2.
     * @return Employees1View2
     */
    public ViewObjectImpl getEmployees1View2() {
        return (ViewObjectImpl) findViewObject("Employees1View2");
    }

    /**
     * Container's getter for Employees1View3.
     * @return Employees1View3
     */
    public ViewObjectImpl getEmployees1View3() {
        return (ViewObjectImpl) findViewObject("Employees1View3");
    }

    /**
     * Container's getter for Employees1View4.
     * @return Employees1View4
     */
    public ViewObjectImpl getEmployees1View4() {
        return (ViewObjectImpl) findViewObject("Employees1View4");
    }

    /**
     * Container's getter for JobHistory1View2.
     * @return JobHistory1View2
     */
    public ViewObjectImpl getJobHistory1View2() {
        return (ViewObjectImpl) findViewObject("JobHistory1View2");
    }

    /**
     * Container's getter for JobHistory1View3.
     * @return JobHistory1View3
     */
    public ViewObjectImpl getJobHistory1View3() {
        return (ViewObjectImpl) findViewObject("JobHistory1View3");
    }

    /**
     * Container's getter for JobHistory1View4.
     * @return JobHistory1View4
     */
    public ViewObjectImpl getJobHistory1View4() {
        return (ViewObjectImpl) findViewObject("JobHistory1View4");
    }

    /**
     * Container's getter for Departments2View3.
     * @return Departments2View3
     */
    public ViewObjectImpl getDepartments2View3() {
        return (ViewObjectImpl) findViewObject("Departments2View3");
    }

    /**
     * Container's getter for Locations1View2.
     * @return Locations1View2
     */
    public ViewObjectImpl getLocations1View2() {
        return (ViewObjectImpl) findViewObject("Locations1View2");
    }

    /**
     * Container's getter for Countries2View2.
     * @return Countries2View2
     */
    public ViewObjectImpl getCountries2View2() {
        return (ViewObjectImpl) findViewObject("Countries2View2");
    }

    /**
     * Container's getter for Locations1View1_2.
     * @return Locations1View1_2
     */
    public ViewObjectImpl getLocations1View1_2() {
        return (ViewObjectImpl) findViewObject("Locations1View1_2");
    }

    /**
     * Container's getter for Employees1View1_2.
     * @return Employees1View1_2
     */
    public ViewObjectImpl getEmployees1View1_2() {
        return (ViewObjectImpl) findViewObject("Employees1View1_2");
    }

    /**
     * Container's getter for JobHistory1View1_2.
     * @return JobHistory1View1_2
     */
    public ViewObjectImpl getJobHistory1View1_2() {
        return (ViewObjectImpl) findViewObject("JobHistory1View1_2");
    }

    /**
     * Container's getter for Departments2View1_2.
     * @return Departments2View1_2
     */
    public ViewObjectImpl getDepartments2View1_2() {
        return (ViewObjectImpl) findViewObject("Departments2View1_2");
    }

    /**
     * Container's getter for Employees1View1_3.
     * @return Employees1View1_3
     */
    public ViewObjectImpl getEmployees1View1_3() {
        return (ViewObjectImpl) findViewObject("Employees1View1_3");
    }

    /**
     * Container's getter for JobHistory1View1_3.
     * @return JobHistory1View1_3
     */
    public ViewObjectImpl getJobHistory1View1_3() {
        return (ViewObjectImpl) findViewObject("JobHistory1View1_3");
    }

    /**
     * Container's getter for Employees1View1_4.
     * @return Employees1View1_4
     */
    public ViewObjectImpl getEmployees1View1_4() {
        return (ViewObjectImpl) findViewObject("Employees1View1_4");
    }

    /**
     * Container's getter for JobHistory1View1_4.
     * @return JobHistory1View1_4
     */
    public ViewObjectImpl getJobHistory1View1_4() {
        return (ViewObjectImpl) findViewObject("JobHistory1View1_4");
    }

    /**
     * Container's getter for Departments2View1_3.
     * @return Departments2View1_3
     */
    public ViewObjectImpl getDepartments2View1_3() {
        return (ViewObjectImpl) findViewObject("Departments2View1_3");
    }

    /**
     * Container's getter for Countries2View1_2.
     * @return Countries2View1_2
     */
    public ViewObjectImpl getCountries2View1_2() {
        return (ViewObjectImpl) findViewObject("Countries2View1_2");
    }

    /**
     * Container's getter for DeptMgrFkAssoc1Link1.
     * @return DeptMgrFkAssoc1Link1
     */
    public ViewLinkImpl getDeptMgrFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkAssoc1Link1");
    }

    /**
     * Container's getter for EmpManagerFkAssoc1Link1.
     * @return EmpManagerFkAssoc1Link1
     */
    public ViewLinkImpl getEmpManagerFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkAssoc1Link1");
    }

    /**
     * Container's getter for EmpDeptFkAssoc1Link1.
     * @return EmpDeptFkAssoc1Link1
     */
    public ViewLinkImpl getEmpDeptFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkAssoc1Link1");
    }

    /**
     * Container's getter for EmpJobFkAssoc1Link1.
     * @return EmpJobFkAssoc1Link1
     */
    public ViewLinkImpl getEmpJobFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("EmpJobFkAssoc1Link1");
    }

    /**
     * Container's getter for JhistDeptFkAssoc1Link1.
     * @return JhistDeptFkAssoc1Link1
     */
    public ViewLinkImpl getJhistDeptFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("JhistDeptFkAssoc1Link1");
    }

    /**
     * Container's getter for JhistEmpFkAssoc1Link1.
     * @return JhistEmpFkAssoc1Link1
     */
    public ViewLinkImpl getJhistEmpFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("JhistEmpFkAssoc1Link1");
    }

    /**
     * Container's getter for JhistJobFkAssoc1Link1.
     * @return JhistJobFkAssoc1Link1
     */
    public ViewLinkImpl getJhistJobFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("JhistJobFkAssoc1Link1");
    }

    /**
     * Container's getter for DeptLocFkAssoc1Link1.
     * @return DeptLocFkAssoc1Link1
     */
    public ViewLinkImpl getDeptLocFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("DeptLocFkAssoc1Link1");
    }

    /**
     * Container's getter for LocCIdFkAssoc1Link1.
     * @return LocCIdFkAssoc1Link1
     */
    public ViewLinkImpl getLocCIdFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("LocCIdFkAssoc1Link1");
    }

    /**
     * Container's getter for CountrRegFkAssoc1Link1.
     * @return CountrRegFkAssoc1Link1
     */
    public ViewLinkImpl getCountrRegFkAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("CountrRegFkAssoc1Link1");
    }

    /**
     * Container's getter for LocCIdFkLink2_1.
     * @return LocCIdFkLink2_1
     */
    public ViewLinkImpl getLocCIdFkLink2_1() {
        return (ViewLinkImpl) findViewLink("LocCIdFkLink2_1");
    }

    /**
     * Container's getter for EmpDeptFkLink2_1.
     * @return EmpDeptFkLink2_1
     */
    public ViewLinkImpl getEmpDeptFkLink2_1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkLink2_1");
    }

    /**
     * Container's getter for JhistDeptFkLink2_1.
     * @return JhistDeptFkLink2_1
     */
    public ViewLinkImpl getJhistDeptFkLink2_1() {
        return (ViewLinkImpl) findViewLink("JhistDeptFkLink2_1");
    }

    /**
     * Container's getter for DeptMgrFkLink2_1.
     * @return DeptMgrFkLink2_1
     */
    public ViewLinkImpl getDeptMgrFkLink2_1() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkLink2_1");
    }

    /**
     * Container's getter for EmpManagerFkLink2_1.
     * @return EmpManagerFkLink2_1
     */
    public ViewLinkImpl getEmpManagerFkLink2_1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink2_1");
    }

    /**
     * Container's getter for JhistEmpFkLink2_1.
     * @return JhistEmpFkLink2_1
     */
    public ViewLinkImpl getJhistEmpFkLink2_1() {
        return (ViewLinkImpl) findViewLink("JhistEmpFkLink2_1");
    }

    /**
     * Container's getter for EmpJobFkLink1_1.
     * @return EmpJobFkLink1_1
     */
    public ViewLinkImpl getEmpJobFkLink1_1() {
        return (ViewLinkImpl) findViewLink("EmpJobFkLink1_1");
    }

    /**
     * Container's getter for JhistJobFkLink1_1.
     * @return JhistJobFkLink1_1
     */
    public ViewLinkImpl getJhistJobFkLink1_1() {
        return (ViewLinkImpl) findViewLink("JhistJobFkLink1_1");
    }

    /**
     * Container's getter for DeptLocFkLink1_1.
     * @return DeptLocFkLink1_1
     */
    public ViewLinkImpl getDeptLocFkLink1_1() {
        return (ViewLinkImpl) findViewLink("DeptLocFkLink1_1");
    }

    /**
     * Container's getter for CountrRegFkLink1_1.
     * @return CountrRegFkLink1_1
     */
    public ViewLinkImpl getCountrRegFkLink1_1() {
        return (ViewLinkImpl) findViewLink("CountrRegFkLink1_1");
    }

    /**
     * Container's getter for Countries3View1.
     * @return Countries3View1
     */
    public ViewObjectImpl getCountries3View1() {
        return (ViewObjectImpl) findViewObject("Countries3View1");
    }

    /**
     * Container's getter for Departments3View1.
     * @return Departments3View1
     */
    public ViewObjectImpl getDepartments3View1() {
        return (ViewObjectImpl) findViewObject("Departments3View1");
    }

    /**
     * Container's getter for EmpDetailsView2View1.
     * @return EmpDetailsView2View1
     */
    public ViewObjectImpl getEmpDetailsView2View1() {
        return (ViewObjectImpl) findViewObject("EmpDetailsView2View1");
    }

    /**
     * Container's getter for Employees2View1.
     * @return Employees2View1
     */
    public ViewObjectImpl getEmployees2View1() {
        return (ViewObjectImpl) findViewObject("Employees2View1");
    }

    /**
     * Container's getter for JobHistory2View1.
     * @return JobHistory2View1
     */
    public ViewObjectImpl getJobHistory2View1() {
        return (ViewObjectImpl) findViewObject("JobHistory2View1");
    }

    /**
     * Container's getter for Jobs3View1.
     * @return Jobs3View1
     */
    public ViewObjectImpl getJobs3View1() {
        return (ViewObjectImpl) findViewObject("Jobs3View1");
    }

    /**
     * Container's getter for Locations2View1.
     * @return Locations2View1
     */
    public ViewObjectImpl getLocations2View1() {
        return (ViewObjectImpl) findViewObject("Locations2View1");
    }

    /**
     * Container's getter for PsTxn2View1.
     * @return PsTxn2View1
     */
    public ViewObjectImpl getPsTxn2View1() {
        return (ViewObjectImpl) findViewObject("PsTxn2View1");
    }

    /**
     * Container's getter for Regions2View1.
     * @return Regions2View1
     */
    public ViewObjectImpl getRegions2View1() {
        return (ViewObjectImpl) findViewObject("Regions2View1");
    }

    /**
     * Container's getter for Countries3View1_1.
     * @return Countries3View1_1
     */
    public ViewObjectImpl getCountries3View1_1() {
        return (ViewObjectImpl) findViewObject("Countries3View1_1");
    }

    /**
     * Container's getter for Departments3View1_1.
     * @return Departments3View1_1
     */
    public ViewObjectImpl getDepartments3View1_1() {
        return (ViewObjectImpl) findViewObject("Departments3View1_1");
    }

    /**
     * Container's getter for Employees2View1_1.
     * @return Employees2View1_1
     */
    public ViewObjectImpl getEmployees2View1_1() {
        return (ViewObjectImpl) findViewObject("Employees2View1_1");
    }

    /**
     * Container's getter for EmpDetailsView2View1_1.
     * @return EmpDetailsView2View1_1
     */
    public ViewObjectImpl getEmpDetailsView2View1_1() {
        return (ViewObjectImpl) findViewObject("EmpDetailsView2View1_1");
    }

    /**
     * Container's getter for Jobs3View1_1.
     * @return Jobs3View1_1
     */
    public ViewObjectImpl getJobs3View1_1() {
        return (ViewObjectImpl) findViewObject("Jobs3View1_1");
    }

    /**
     * Container's getter for JobHistory2View1_1.
     * @return JobHistory2View1_1
     */
    public ViewObjectImpl getJobHistory2View1_1() {
        return (ViewObjectImpl) findViewObject("JobHistory2View1_1");
    }

    /**
     * Container's getter for Locations2View1_1.
     * @return Locations2View1_1
     */
    public ViewObjectImpl getLocations2View1_1() {
        return (ViewObjectImpl) findViewObject("Locations2View1_1");
    }

    /**
     * Container's getter for PsTxn2View1_1.
     * @return PsTxn2View1_1
     */
    public ViewObjectImpl getPsTxn2View1_1() {
        return (ViewObjectImpl) findViewObject("PsTxn2View1_1");
    }

    /**
     * Container's getter for Regions2View1_1.
     * @return Regions2View1_1
     */
    public ViewObjectImpl getRegions2View1_1() {
        return (ViewObjectImpl) findViewObject("Regions2View1_1");
    }

    /**
     * Container's getter for Departments3View2.
     * @return Departments3View2
     */
    public ViewObjectImpl getDepartments3View2() {
        return (ViewObjectImpl) findViewObject("Departments3View2");
    }

    /**
     * Container's getter for Employees2View2.
     * @return Employees2View2
     */
    public ViewObjectImpl getEmployees2View2() {
        return (ViewObjectImpl) findViewObject("Employees2View2");
    }

    /**
     * Container's getter for Employees2View3.
     * @return Employees2View3
     */
    public ViewObjectImpl getEmployees2View3() {
        return (ViewObjectImpl) findViewObject("Employees2View3");
    }

    /**
     * Container's getter for Employees2View4.
     * @return Employees2View4
     */
    public ViewObjectImpl getEmployees2View4() {
        return (ViewObjectImpl) findViewObject("Employees2View4");
    }

    /**
     * Container's getter for JobHistory2View2.
     * @return JobHistory2View2
     */
    public ViewObjectImpl getJobHistory2View2() {
        return (ViewObjectImpl) findViewObject("JobHistory2View2");
    }

    /**
     * Container's getter for JobHistory2View3.
     * @return JobHistory2View3
     */
    public ViewObjectImpl getJobHistory2View3() {
        return (ViewObjectImpl) findViewObject("JobHistory2View3");
    }

    /**
     * Container's getter for JobHistory2View4.
     * @return JobHistory2View4
     */
    public ViewObjectImpl getJobHistory2View4() {
        return (ViewObjectImpl) findViewObject("JobHistory2View4");
    }

    /**
     * Container's getter for Departments3View3.
     * @return Departments3View3
     */
    public ViewObjectImpl getDepartments3View3() {
        return (ViewObjectImpl) findViewObject("Departments3View3");
    }

    /**
     * Container's getter for Locations2View2.
     * @return Locations2View2
     */
    public ViewObjectImpl getLocations2View2() {
        return (ViewObjectImpl) findViewObject("Locations2View2");
    }

    /**
     * Container's getter for Countries3View2.
     * @return Countries3View2
     */
    public ViewObjectImpl getCountries3View2() {
        return (ViewObjectImpl) findViewObject("Countries3View2");
    }

    /**
     * Container's getter for Locations2View1_2.
     * @return Locations2View1_2
     */
    public ViewObjectImpl getLocations2View1_2() {
        return (ViewObjectImpl) findViewObject("Locations2View1_2");
    }

    /**
     * Container's getter for Employees2View1_2.
     * @return Employees2View1_2
     */
    public ViewObjectImpl getEmployees2View1_2() {
        return (ViewObjectImpl) findViewObject("Employees2View1_2");
    }

    /**
     * Container's getter for JobHistory2View1_2.
     * @return JobHistory2View1_2
     */
    public ViewObjectImpl getJobHistory2View1_2() {
        return (ViewObjectImpl) findViewObject("JobHistory2View1_2");
    }

    /**
     * Container's getter for Departments3View1_2.
     * @return Departments3View1_2
     */
    public ViewObjectImpl getDepartments3View1_2() {
        return (ViewObjectImpl) findViewObject("Departments3View1_2");
    }

    /**
     * Container's getter for Employees2View1_3.
     * @return Employees2View1_3
     */
    public ViewObjectImpl getEmployees2View1_3() {
        return (ViewObjectImpl) findViewObject("Employees2View1_3");
    }

    /**
     * Container's getter for JobHistory2View1_3.
     * @return JobHistory2View1_3
     */
    public ViewObjectImpl getJobHistory2View1_3() {
        return (ViewObjectImpl) findViewObject("JobHistory2View1_3");
    }

    /**
     * Container's getter for Employees2View1_4.
     * @return Employees2View1_4
     */
    public ViewObjectImpl getEmployees2View1_4() {
        return (ViewObjectImpl) findViewObject("Employees2View1_4");
    }

    /**
     * Container's getter for JobHistory2View1_4.
     * @return JobHistory2View1_4
     */
    public ViewObjectImpl getJobHistory2View1_4() {
        return (ViewObjectImpl) findViewObject("JobHistory2View1_4");
    }

    /**
     * Container's getter for Departments3View1_3.
     * @return Departments3View1_3
     */
    public ViewObjectImpl getDepartments3View1_3() {
        return (ViewObjectImpl) findViewObject("Departments3View1_3");
    }

    /**
     * Container's getter for Countries3View1_2.
     * @return Countries3View1_2
     */
    public ViewObjectImpl getCountries3View1_2() {
        return (ViewObjectImpl) findViewObject("Countries3View1_2");
    }

    /**
     * Container's getter for DeptMgrFkAssoc2Link1.
     * @return DeptMgrFkAssoc2Link1
     */
    public ViewLinkImpl getDeptMgrFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkAssoc2Link1");
    }

    /**
     * Container's getter for EmpManagerFkAssoc2Link1.
     * @return EmpManagerFkAssoc2Link1
     */
    public ViewLinkImpl getEmpManagerFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkAssoc2Link1");
    }

    /**
     * Container's getter for EmpDeptFkAssoc2Link1.
     * @return EmpDeptFkAssoc2Link1
     */
    public ViewLinkImpl getEmpDeptFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkAssoc2Link1");
    }

    /**
     * Container's getter for EmpJobFkAssoc2Link1.
     * @return EmpJobFkAssoc2Link1
     */
    public ViewLinkImpl getEmpJobFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("EmpJobFkAssoc2Link1");
    }

    /**
     * Container's getter for JhistDeptFkAssoc2Link1.
     * @return JhistDeptFkAssoc2Link1
     */
    public ViewLinkImpl getJhistDeptFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("JhistDeptFkAssoc2Link1");
    }

    /**
     * Container's getter for JhistEmpFkAssoc2Link1.
     * @return JhistEmpFkAssoc2Link1
     */
    public ViewLinkImpl getJhistEmpFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("JhistEmpFkAssoc2Link1");
    }

    /**
     * Container's getter for JhistJobFkAssoc2Link1.
     * @return JhistJobFkAssoc2Link1
     */
    public ViewLinkImpl getJhistJobFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("JhistJobFkAssoc2Link1");
    }

    /**
     * Container's getter for DeptLocFkAssoc2Link1.
     * @return DeptLocFkAssoc2Link1
     */
    public ViewLinkImpl getDeptLocFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("DeptLocFkAssoc2Link1");
    }

    /**
     * Container's getter for LocCIdFkAssoc2Link1.
     * @return LocCIdFkAssoc2Link1
     */
    public ViewLinkImpl getLocCIdFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("LocCIdFkAssoc2Link1");
    }

    /**
     * Container's getter for CountrRegFkAssoc2Link1.
     * @return CountrRegFkAssoc2Link1
     */
    public ViewLinkImpl getCountrRegFkAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("CountrRegFkAssoc2Link1");
    }

    /**
     * Container's getter for LocCIdFkLink3_1.
     * @return LocCIdFkLink3_1
     */
    public ViewLinkImpl getLocCIdFkLink3_1() {
        return (ViewLinkImpl) findViewLink("LocCIdFkLink3_1");
    }

    /**
     * Container's getter for EmpDeptFkLink3_1.
     * @return EmpDeptFkLink3_1
     */
    public ViewLinkImpl getEmpDeptFkLink3_1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkLink3_1");
    }

    /**
     * Container's getter for JhistDeptFkLink3_1.
     * @return JhistDeptFkLink3_1
     */
    public ViewLinkImpl getJhistDeptFkLink3_1() {
        return (ViewLinkImpl) findViewLink("JhistDeptFkLink3_1");
    }

    /**
     * Container's getter for DeptMgrFkLink3_1.
     * @return DeptMgrFkLink3_1
     */
    public ViewLinkImpl getDeptMgrFkLink3_1() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkLink3_1");
    }

    /**
     * Container's getter for EmpManagerFkLink3_1.
     * @return EmpManagerFkLink3_1
     */
    public ViewLinkImpl getEmpManagerFkLink3_1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink3_1");
    }

    /**
     * Container's getter for JhistEmpFkLink3_1.
     * @return JhistEmpFkLink3_1
     */
    public ViewLinkImpl getJhistEmpFkLink3_1() {
        return (ViewLinkImpl) findViewLink("JhistEmpFkLink3_1");
    }

    /**
     * Container's getter for EmpJobFkLink2_1.
     * @return EmpJobFkLink2_1
     */
    public ViewLinkImpl getEmpJobFkLink2_1() {
        return (ViewLinkImpl) findViewLink("EmpJobFkLink2_1");
    }

    /**
     * Container's getter for JhistJobFkLink2_1.
     * @return JhistJobFkLink2_1
     */
    public ViewLinkImpl getJhistJobFkLink2_1() {
        return (ViewLinkImpl) findViewLink("JhistJobFkLink2_1");
    }

    /**
     * Container's getter for DeptLocFkLink2_1.
     * @return DeptLocFkLink2_1
     */
    public ViewLinkImpl getDeptLocFkLink2_1() {
        return (ViewLinkImpl) findViewLink("DeptLocFkLink2_1");
    }

    /**
     * Container's getter for CountrRegFkLink2_1.
     * @return CountrRegFkLink2_1
     */
    public ViewLinkImpl getCountrRegFkLink2_1() {
        return (ViewLinkImpl) findViewLink("CountrRegFkLink2_1");
    }
}

