package model;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 18 14:21:33 NOVT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HighlPaidEmployeesImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HighlPaidEmployeesImpl() {
    }
}

