package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 18 15:51:23 NOVT 2017
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void DeleteAllEmps();
}

